name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: '0 */4 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_30_days
          SHOW_TOTAL : true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_PROFILE_VIEWS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LOC_CHART: true
          SHOW_LINES_OF_CODE: true
          SHOW_SHORT_INFO: true


# name: Waka Readme

# on:
#   schedule:
#     # Runs every 4 hours
#     - cron: '0 */4 * * *'
#   workflow_dispatch:

# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           SHOW_OS: "True"
#           SHOW_PROJECTS: "True"
#           SHOW_PROFILE_VIEWS: "False"
#           SHOW_EDITORS: "False"
#           SHOW_LANGUAGE_PER_REPO: "True"
#           SHOW_LOC_CHART: "False"
#           SHOW_LINES_OF_CODE: "True"
#           SHOW_SHORT_INFO: "False"